"""Prompt-building and LLM client package exports."""

from .client import (
    LLMClient,
    LLMError,
    LLMHttpError,
    LLMRateLimited,
    LLMRequest,
    LLMResponse,
    LLMSchemaError,
    LLMTimeoutError,
    LLMUnauthorized,
    MockLLMClient,
    OpenAICompatibleClient,
    get_llm_client,
    retry_chat_complete,
)
from .fallback import STUB_DEATH_REPORT, STUB_DIRECTOR, STUB_PRESS_EVAL, get_default_stub
from .parser import (
    ParseError,
    ParseExtractionError,
    ParseSchemaError,
    clamp_metrics_delta,
    extract_json_block,
    parse_death_report,
    parse_director,
    parse_press_eval,
    parse_with_fallback,
)
from .prompt_builder import (
    PROMPT_TEMPLATE_DEATH_REPORT,
    PROMPT_TEMPLATE_DIRECTOR,
    PROMPT_TEMPLATE_PRESS_EVAL,
    PromptBuilder,
    PromptBundle,
    _escape_user_input,
)
from .schema import (
    BoardReactionRaw,
    DeathReportRaw,
    DirectorRaw,
    EmployeeGossipRaw,
    MediaHeadlineRaw,
    PressEvalRaw,
    RivalActionRaw,
)

__all__ = (
    "BoardReactionRaw",
    "DeathReportRaw",
    "DirectorRaw",
    "EmployeeGossipRaw",
    "LLMClient",
    "LLMError",
    "LLMHttpError",
    "LLMRateLimited",
    "LLMRequest",
    "LLMResponse",
    "LLMSchemaError",
    "LLMTimeoutError",
    "LLMUnauthorized",
    "MockLLMClient",
    "MediaHeadlineRaw",
    "OpenAICompatibleClient",
    "ParseError",
    "ParseExtractionError",
    "ParseSchemaError",
    "PROMPT_TEMPLATE_DEATH_REPORT",
    "PROMPT_TEMPLATE_DIRECTOR",
    "PROMPT_TEMPLATE_PRESS_EVAL",
    "PressEvalRaw",
    "RivalActionRaw",
    "STUB_DEATH_REPORT",
    "STUB_DIRECTOR",
    "STUB_PRESS_EVAL",
    "PromptBuilder",
    "PromptBundle",
    "_escape_user_input",
    "clamp_metrics_delta",
    "extract_json_block",
    "get_default_stub",
    "get_llm_client",
    "parse_death_report",
    "parse_director",
    "parse_press_eval",
    "parse_with_fallback",
    "retry_chat_complete",
)
